services:
  back:
    container_name: backend-java
    build: ./backend/Dockerfile
    ports:
      - 8080:8080
    environment:
      POSTGRES_HOST: db:5432
      DB_NAME: push_service
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db
  db:
    container_name: postgres-db
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: push_service
