GET http://localhost:8080/notifications/my?page=0&size=20
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTQwMDExMjUsInVzZXJJZCI6MywidXNlcm5hbWUiOiLQn9Cw0LLQtdC7Iiwicm9sZSI6IlVTRVIifQ.WQ5NnLMg_ExgeRvy44gXhAYWLcC8dX-Vgb1S3vmQEU3MM9WJ9Q3DJzamsvKNB_4dminItrg4UDUwlkXCQQF7Jw